<?php

/**
 * The file is part of the "webifycms/site", WebifyCMS site.
 *
 * @see https://webifycms.com
 *
 * @copyright Copyright (c) 2026 WebifyCMS
 * @license https://webifycms.com/license
 * @author Mohammed Shifreen <mshifreen@gmail.com>
 */
declare(strict_types=1);

namespace App\Infrastructure\Persistence\Filesystem;

use League\CommonMark\ConverterInterface;
use League\CommonMark\Exception\CommonMarkException;
use League\Config\Exception\ConfigurationExceptionInterface;
use Psr\Cache\InvalidArgumentException;
use Psr\Log\LoggerInterface;
use Symfony\Contracts\Cache\CacheInterface;
use Webify\Base\Application\Service\ConfigInterface;

/**
 * Reads posts from a JSON index and individual Markdown files.
 *
 * The index (posts.json) is generated by the `posts:generate-index` console
 * command and contains all post-metadata sorted newest-first.
 *
 * The full post-content (title, slug, date, excerpt, body, html) is built on demand and
 * cached via the Symfony cache adapter.
 *
 * @phpstan-type PostMeta array{
 *     title: string,
 *     slug: string,
 *     date: string,
 *     excerpt: string,
 *     file: string,
 * }
 * @phpstan-type Post array{
 *     title: string,
 *     slug: string,
 *     date: string,
 *     excerpt: string,
 *     body: string,
 *     html: string,
 * }
 */
final readonly class PostReader
{
	/**
	 * @var string the path to the posts directory
	 */
	private string $path;

	/**
	 * The constructor.
	 */
	public function __construct(
		private ConfigInterface $config,
		private ConverterInterface $converter,
		private LoggerInterface $logger,
		private CacheInterface $cache,
	) {
		$this->path = $this->config->basePath . '/resources/posts';
	}

	/**
	 * Finds a post by its unique slug.
	 *
	 * Looks up the slug in the JSON index, then reads the corresponding
	 * Markdown file, and converts it to HTML. The result is cached so that
	 * the Markdown is only parsed once per TTL window.
	 *
	 * @return null|Post
	 *
	 * @throws InvalidArgumentException
	 */
	public function findBySlug(string $slug): ?array
	{
		$entry = array_find($this->loadIndex(), fn ($item) => $item['slug'] === $slug);

		if (null === $entry) {
			return null;
		}

		/** @var PostMeta $entry */
		return $this->cache->get('post_' . $slug, function () use ($entry): array {
			$mdPath = $this->path . '/' . $entry['file'];
			$body   = file_get_contents($mdPath);
			$body   = false === $body ? '' : $body;

			$body = $this->stripFrontMatter($body);

			try {
				$html = $this->converter->convert($body);
			} catch (CommonMarkException $exception) {
				$this->logger->error('Failed to convert markdown to HTML', [
					'exception' => $exception,
					'slug'      => $entry['slug'],
				]);

				$html = '';
			} catch (ConfigurationExceptionInterface $exception) {
				$this->logger->error('Failed to convert markdown to HTML', [
					'exception' => $exception,
				]);

				$html = '';
			}

			return [
				'title'   => $entry['title'],
				'slug'    => $entry['slug'],
				'date'    => $entry['date'],
				'excerpt' => $entry['excerpt'],
				'body'    => $body,
				'html'    => $html,
			];
		}, $this->config->get('cache.lifetime', 3600));
	}

	/**
	 * Returns all post-metadata from the JSON index.
	 *
	 * No Markdown files are read — only the pre-built index is decoded.
	 * Use this for listing pages that need only title, slug, date, excerpt.
	 *
	 * @return PostMeta[]
	 */
	public function findAll(): array
	{
		return $this->loadIndex();
	}

	/**
	 * Returns the total number of posts.
	 */
	public function count(): int
	{
		return count($this->loadIndex());
	}

	/**
	 * Returns the previous and next post metadata for a given slug.
	 *
	 * Determines position from the sorted JSON index and returns only
	 * the adjacent metadata — no Markdown is read or converted.
	 *
	 * @return array{prev: null|PostMeta, next: null|PostMeta}
	 */
	public function findAdjacent(string $slug): array
	{
		$index = $this->loadIndex();
		$prev  = null;
		$next  = null;

		foreach ($index as $i => $item) {
			if ($item['slug'] !== $slug) {
				continue;
			}

			if (isset($index[$i + 1])) {
				$prev = $index[$i + 1];
			}

			if (isset($index[$i - 1])) {
				$next = $index[$i - 1];
			}

			break;
		}

		return ['prev' => $prev, 'next' => $next];
	}

	/**
	 * Strips YAML front matter (delimited by ---) from the markdown body.
	 */
	private function stripFrontMatter(string $body): string
	{
		if (str_starts_with($body, '---')) {
			$end = strpos($body, '---', 3);

			if (false !== $end) {
				return substr($body, $end + 3);
			}
		}

		return $body;
	}

	/**
	 * Reads and decodes the posts.json index file.
	 *
	 * @return list<PostMeta>
	 */
	private function loadIndex(): array
	{
		$path = $this->path . '/posts.json';

		if (!file_exists($path)) {
			return [];
		}

		$contents = file_get_contents($path);

		if (false === $contents) {
			return [];
		}

		/** @var null|list<PostMeta> $data */
		$data = json_decode($contents, true);

		return is_array($data) ? $data : [];
	}
}
